// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

// This contract manages the registry of academic record hashes.
contract StudentRecordsRegistry is Ownable {

    // Maps a unique record identifier (bytes32) to the immutable document hash (bytes32).
    // The record identifier can be generated by hashing a combination of: 
    // UniversityID, StudentID, and a RecordSequenceNumber.
    mapping(bytes32 => bytes32) private records;

    // Event emitted whenever a new record is successfully issued.
    event RecordIssued(
        bytes32 indexed recordIdentifier,
        address indexed issuerAddress,
        bytes32 documentHash,
        uint256 timestamp
    );

    // Constructor: Sets the deployer's address as the initial owner (the University).
    // The deployer is the only address allowed to call onlyOwner functions.
    constructor(address initialOwner) Ownable(initialOwner) {}

    // ----------------------------------------------------------------
    // 1. ISSUANCE FUNCTION (WRITE)
    // ----------------------------------------------------------------

    /**
     * @dev Allows the owner (University) to issue a new academic record.
     * @param _recordIdentifier Unique ID for the record (e.g., hash of metadata).
     * @param _documentHash The SHA-256 hash of the off-chain PDF/file.
     */
    function issueRecord(
        bytes32 _recordIdentifier,
        bytes32 _documentHash
    ) public onlyOwner {
        // Validation: Ensure the record hasn't been issued before.
        // If records[_recordIdentifier] is not zero, the hash exists.
        require(records[_recordIdentifier] == 0, "Record already issued. Cannot be overwritten.");
        
        // Storage: Store the immutable hash.
        records[_recordIdentifier] = _documentHash;

        // Logging: Emit an event for easy tracking by off-chain services.
        emit RecordIssued(_recordIdentifier, msg.sender, _documentHash, block.timestamp);
    }

    // ----------------------------------------------------------------
    // 2. VERIFICATION FUNCTION (READ)
    // ----------------------------------------------------------------
    
    /**
     * @dev Allows any public user or verifier to retrieve the official hash 
     * associated with a record ID. This is the core verification step.
     * @param _recordIdentifier The unique ID of the record to check.
     * @return The official document hash stored on the blockchain.
     */
    function getRecordHash(
        bytes32 _recordIdentifier
    ) public view returns (bytes32) {
        // Validation: Ensure the record exists before returning.
        require(records[_recordIdentifier] != 0, "Record not found in the registry.");
        return records[_recordIdentifier];
    }
}