/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentRecordsRegistry } from './StudentRecordsRegistry.js';
export * as factories from './factories/index.js';
export { StudentRecordsRegistry__factory } from './factories/StudentRecordsRegistry__factory.js';